In [6]:
print("Teste do JupyterLab")

Teste do JupyterLab


Alguns atalhos de teclado (funcionam quando a célula não está no modo de edição -> apertando ESC):

a: cria uma célula antes

b: cria uma célula depois

d + d ('d' duas vezes): exclui a célula

m: converte a célula em Markdown

Ctrl + Enter: Executa ou Renderiza (se for Markdown) a célula

Shift + Enter: Executa e cria (ou avança para) nova linha de código

In [12]:
1 + 1

2

In [8]:
1 == 2

False

## Exemplos de uso de Numpy

In [16]:
import numpy as np

In [18]:
a = np.arange(15).reshape(3, 5)

In [19]:
b = np.arange(7, 71, 7)  # o valor 'stop' (não é incluído no vetor)
b

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [21]:
c = np.eye(4)  # matriz identidade
c

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [37]:
d = np.empty( (2,3) )
d

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
lista = [1, 2, 3, 4]

In [42]:
e = np.array(lista)
e

array([1, 2, 3, 4])

In [45]:
f = e.reshape(2,2)
f

array([[1, 2],
       [3, 4]])